"""Refuse to commit secrets, runtime data or local AI/planning documents.

Run by the pre-commit hook (.githooks/pre-commit) against staged files, and
usable by hand:  uv run python scripts/check_secrets.py [--all]
Exit code 1 lists every problem found.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]

BLOCKED_PATHS = [
    re.compile(p) for p in (
        r"(^|/)data/", r"(^|/)config\.ya?ml$", r"(^|/)secret\.key$", r"\.key$", r"\.pem$",
        r"(^|/)\.env(\..*)?$", r"\.sqlite3(-.*)?$", r"(^|/)secrets\.ya?ml$",
        r"(^|/)CLAUDE(\.local)?\.md$", r"(^|/)\.claude/", r"(^|/)plans/", r"\.plan\.md$",
        r"\.bak$", r"\.sqlite3\.", r"\.invalid.*\.ya?ml$",
    )
]
# Allow-list for files whose names look risky but are safe templates.
ALLOWED_PATHS = [re.compile(p) for p in (r"^esphome/secrets\.example\.yaml$",)]
# tests/fixtures/v<N>/: made-up config/DB from a previous release, generated by the script beside
# them; the migration tests need real files.  They are still scanned: the only secrets allowed in
# them are the fixture's own made-up values below (PIN 1234 hash, key bytes 0x00..0x1f, and the
# legacy ESPHome password placeholder).
FIXTURE_PATHS = re.compile(r"^tests/fixtures/v[0-9]{1,2}/(config\.yaml|stagewatch\.sqlite3)$")
FIXTURE_ALLOWED_VALUES = (
    "pbkdf2_sha256$200000$G0X5/WUxy5qIKk6NAv9mcg==$8IPIz0/7X1ne4KYSIPdRUMkNbGtRbtNxCRwFErrG5so=",
    "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=",
    "password: fixture-legacy-api-password",
)
FIXTURE_EXTRA_PATTERNS = [
    ("ESPHome encryption key", re.compile(r"[A-Za-z0-9+/]{43}=")),
    ("password", re.compile(r"password\s*:\s*[\"']?[^\s\"']+", re.I)),
]

SECRET_PATTERNS = [
    ("private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("ESPHome API key", re.compile(r"\bkey:\s*[\"']?[A-Za-z0-9+/]{43}=[\"']?")),
    ("admin PIN hash", re.compile(r"pbkdf2_sha256\$\d+\$")),
    ("GitHub token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b")),
    ("AWS key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("Wi-Fi password", re.compile(r"^\s*password:\s*[\"'](?!!secret)[^\"']{6,}[\"']", re.M)),
]


def staged_files() -> list[str]:
    out = subprocess.run(["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
                         cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return [line for line in out.splitlines() if line]


def all_files() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True,
                         check=True).stdout
    return [line for line in out.splitlines() if line]


def staged_content(path: str, staged: bool, binary_ok: bool = False) -> str:
    if staged:
        res = subprocess.run(["git", "show", f":{path}"], cwd=ROOT, capture_output=True)
        data = res.stdout
    else:
        data = (ROOT / path).read_bytes()
    if b"\0" in data[:4096] and not binary_ok:
        return ""  # binary
    return data.decode("utf-8", errors="ignore")


def check(paths: list[str], staged: bool) -> list[str]:
    problems = []
    for path in paths:
        posix = str(PurePosixPath(path))
        if any(a.search(posix) for a in ALLOWED_PATHS):
            continue
        if FIXTURE_PATHS.search(posix):
            text = staged_content(path, staged, binary_ok=True)
            for value in FIXTURE_ALLOWED_VALUES:
                text = text.replace(value, "")
            for name, pattern in SECRET_PATTERNS + FIXTURE_EXTRA_PATTERNS:
                if pattern.search(text):
                    problems.append(f"{posix}: fixture looks like it contains a {name} other than the test values")
            continue
        if any(b.search(posix) for b in BLOCKED_PATHS):
            problems.append(f"{posix}: file type must never be committed")
            continue
        if posix == "scripts/check_secrets.py" or posix.startswith("tests/"):
            continue
        text = staged_content(path, staged)
        for name, pattern in SECRET_PATTERNS:
            if pattern.search(text):
                problems.append(f"{posix}: looks like it contains a {name}")
    return problems


def main() -> int:
    use_all = "--all" in sys.argv
    problems = check(all_files() if use_all else staged_files(), staged=not use_all)
    if problems:
        print("Commit blocked: possible secrets or local-only files:\n  " + "\n  ".join(problems))
        print("Unstage them (git restore --staged <file>) or move secrets to a gitignored file.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
