"""Keep an installation's configuration in its own PRIVATE git repository.

The Stagewatch code repo is a blank system. Your site (devices, areas,
calibration, thresholds, dashboards, OSC targets) lives in config.yaml inside
the data folder. This tool turns the data folder into a small git repo that
tracks an explicit allow-list of site files and pushes it to a private remote,
giving you history and an off-machine backup.

Tracked (only these, anchored to the top of the data folder):
  config.yaml, README.md, .gitignore
  branding/events/<id>/logo-*.png|jpg|jpeg|webp
  contacts/*.yaml
  documents/<event>/index.json and documents/<event>/<doc>/r*.md
  documents/templates/**/index.json and documents/templates/**/r*.md
Never tracked: config.yaml.bak and any *.bak (including the *.pre-v*.bak safety copies), *.tmp
and other temp files, *.invalid*.yaml, emulate/, backups/, logs/, secret.key, the
history database with its -wal/-shm files, and updater state.
`push` rewrites .gitignore from this list each time and stops tracking anything
it now excludes. Untracking does not remove files from history already pushed.

config.yaml contains the admin PIN hash and ESPHome API encryption keys, and
contacts/documents hold personal data, so the remote MUST be private. `init` and
`push` check every URL that would be pushed to. They refuse a public GitHub repo,
and refuse any remote they cannot verify as GitHub unless you pass
--allow-unverified-remote (then you are responsible for it being private).

Usage:
    uv run python scripts/site_config.py init  [--data-dir DIR] --remote URL [--allow-unverified-remote]
    uv run python scripts/site_config.py push  [--data-dir DIR] [-m "message"] [--allow-unverified-remote]
    uv run python scripts/site_config.py pull  [--data-dir DIR]
    uv run python scripts/site_config.py status [--data-dir DIR]

--data-dir defaults to the same folder Stagewatch uses ($STAGEWATCH_DATA or the
per-user default). For the Windows boot service use C:\\ProgramData\\Stagewatch;
for the Pi service /var/lib/stagewatch.
Stop Stagewatch before `pull`, then start it again to load the pulled config.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from stagewatch.__main__ import default_data_dir  # noqa: E402

GITIGNORE = """# Generated by scripts/site_config.py on every `push`. Edits are overwritten.
# Allow-list: only the site's own files are tracked. Everything else is ignored.
# Order matters: the re-ignore rules at the bottom come after the allow rules.
# Allow rules are anchored with a leading slash so nested copies stay ignored.
# Anything that writes into contacts/ or documents/ in future must name its temp
# files `.contacts-*`, `.documents-*` or `*.tmp`, or they could be committed.
*
!*/
!/.gitignore
!/README.md
!/config.yaml
!/branding/events/*/logo-*.png
!/branding/events/*/logo-*.jpg
!/branding/events/*/logo-*.jpeg
!/branding/events/*/logo-*.webp
!/contacts/*.yaml
!/documents/*/index.json
!/documents/*/*/r*.md
!/documents/templates/**/index.json
!/documents/templates/**/r*.md
# Never tracked, even where an allow rule above would match.
*.bak
*.tmp
*.tmp.*
*.invalid*.yaml
.config-*
.contacts-*
.documents-*
emulate/
backups/
logs/
secret.key
*.sqlite3
*.sqlite3-wal
*.sqlite3-shm
*.db
*.db-wal
*.db-shm
*.log
updater*.json
.updater*
"""

README = """# Stagewatch site configuration (PRIVATE)

This repository holds one Stagewatch installation's site files: `config.yaml`
(devices, areas, calibration offsets, thresholds, dashboards and OSC targets),
event logos (`branding/events/`), on-site contacts (`contacts/`), and event
documents and templates (`documents/`).

It contains the admin PIN hash and ESPHome API encryption keys, and the contacts and
documents may hold names, phone numbers and other personal data, so **keep this
repository private**. Managed with `scripts/site_config.py` from the Stagewatch
code repository. Which files are tracked is decided by the `.gitignore` allow-list,
which `push` rewrites every time. Untracking a file does not remove it from
history that was already pushed.
"""

GITHUB_HOSTS = {"github.com", "www.github.com"}
SCP_RE = re.compile(r"^(?:[^@/\s]+@)?([^:/\s]+):(?!//)(.+)$")


def parse_github(remote: str) -> tuple[str, str] | None:
    """Return (owner, repo) if the URL is clearly a GitHub repository, else None."""
    remote = remote.strip()
    if "://" in remote:
        try:
            parts = urlsplit(remote)
            host = (parts.hostname or "").lower()
        except ValueError:
            return None
        if parts.scheme.lower() not in {"https", "http", "ssh", "git"} or host not in GITHUB_HOSTS:
            return None
        path = parts.path
    else:
        m = SCP_RE.match(remote)
        if not m or m.group(1).lower() not in GITHUB_HOSTS:
            return None
        path = m.group(2)
    segs = [x for x in path.split("/") if x]
    if len(segs) < 2:
        return None
    owner, repo = segs[0], segs[1]
    if repo.lower().endswith(".git"):
        repo = repo[:-4]
    if owner in {".", ".."} or repo in {".", ".."}:
        return None
    if not re.fullmatch(r"[A-Za-z0-9._-]+", owner) or not re.fullmatch(r"[A-Za-z0-9._-]+", repo):
        return None
    return owner, repo


def _run(cmd: list[str], cwd: Path | None = None, text: bool = True) -> subprocess.CompletedProcess:
    try:
        if text:
            return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                                  encoding="utf-8", errors="replace")
        return subprocess.run(cmd, cwd=cwd, capture_output=True)
    except FileNotFoundError:
        tool = cmd[0]
        extra = " (needed to check that the remote is private)" if tool == "gh" else ""
        sys.exit(f"`{tool}` was not found on this computer{extra}. Install it and try again. "
                 "Nothing was pushed.")


def git(data_dir: Path, *args: str, check: bool = True) -> str:
    res = _run(["git", *args], cwd=data_dir)
    if check and res.returncode != 0:
        sys.exit(f"git {' '.join(args)} failed:\n{res.stderr.strip()}")
    return res.stdout.strip()


def git_z(data_dir: Path, *args: str) -> list[str]:
    """Run git with -z output and split on NUL (safe for any file name)."""
    res = _run(["git", "-c", "core.quotePath=false", *args], cwd=data_dir, text=False)
    if res.returncode != 0:
        sys.exit(f"git {' '.join(args)} failed:\n{res.stderr.decode('utf-8', 'replace').strip()}")
    return [x.decode("utf-8", "surrogateescape") for x in res.stdout.split(b"\0") if x]


def ensure_private(remote: str, allow_unverified: bool = False) -> None:
    """Fail closed: only a GitHub repo that `gh` confirms is private passes."""
    found = parse_github(remote)
    if not found:
        if allow_unverified:
            print(f"warning: can't verify that {remote} is private (not recognised as GitHub). "
                  "You asked to continue; make sure it is private.")
            return
        sys.exit(f"REFUSING: can't verify that {remote} is a private repository (it isn't a "
                 "recognised github.com address). Pass --allow-unverified-remote if you are "
                 "certain it is private.")
    owner, repo = found
    res = _run(["gh", "api", f"repos/{owner}/{repo}"])
    if res.returncode != 0:
        sys.exit(f"Can't read {owner}/{repo} with the GitHub CLI (gh). Create it as private first:\n"
                 f"  gh repo create {owner}/{repo} --private")
    try:
        private = json.loads(res.stdout).get("private") is True
    except (ValueError, AttributeError):
        private = False
    if not private:
        sys.exit(f"REFUSING: {owner}/{repo} is PUBLIC or its visibility could not be confirmed. "
                 "config.yaml contains secrets. Make the repository private first.")


def check_push_targets(data_dir: Path, allow_unverified: bool) -> None:
    """Check every URL `git push origin` would actually use (pushurl included)."""
    urls = git(data_dir, "remote", "get-url", "--push", "--all", "origin").splitlines()
    if not urls:
        sys.exit("The origin remote has no push URL.")
    for url in urls:
        ensure_private(url.strip(), allow_unverified)


def _rm_cached(data_dir: Path, files: list[str]) -> None:
    for i in range(0, len(files), 100):
        git(data_dir, "--literal-pathspecs", "rm", "--cached", "-q", "--", *files[i:i + 100])


def refresh_gitignore(data_dir: Path) -> None:
    """Rewrite .gitignore from the allow-list and stop tracking anything it now ignores."""
    (data_dir / ".gitignore").write_text(GITIGNORE, encoding="utf-8", newline="\n")
    stale = git_z(data_dir, "ls-files", "-z", "-c", "-i", "--exclude-standard")
    if stale:
        _rm_cached(data_dir, stale)
        left = git_z(data_dir, "ls-files", "-z", "-c", "-i", "--exclude-standard")
        if left:
            sys.exit("Could not stop tracking these files, so nothing was pushed:\n  "
                     + "\n  ".join(left))


def _blob(data_dir: Path, oid: str) -> bytes:
    res = _run(["git", "cat-file", "blob", oid], cwd=data_dir, text=False)
    if res.returncode != 0:
        sys.exit(f"Could not read {oid} from the remote.")
    return res.stdout


def check_local_matches_remote(data_dir: Path, ref: str) -> None:
    """Stop if checking out `ref` would overwrite a different local file."""
    differing = []
    for entry in git_z(data_dir, "ls-tree", "-r", "-z", ref):
        meta, _, rel = entry.partition("\t")
        fields = meta.split()
        if len(fields) != 3 or fields[1] != "blob" or rel == ".gitignore":
            continue
        local = data_dir / rel
        if not local.is_file():
            continue
        a = local.read_bytes().replace(b"\r\n", b"\n")
        if a != _blob(data_dir, fields[2]).replace(b"\r\n", b"\n"):
            differing.append(rel)
    if differing:
        sys.exit("This folder and the remote both have these files, with different contents. "
                 "Move one side aside and decide which to keep before running init again:\n  "
                 + "\n  ".join(differing))


def cmd_init(data_dir: Path, remote: str, allow_unverified: bool = False) -> None:
    ensure_private(remote, allow_unverified)
    data_dir.mkdir(parents=True, exist_ok=True)
    fresh = not (data_dir / ".git").exists()
    if fresh:
        git(data_dir, "init", "-q", "-b", "main")
    remotes = git(data_dir, "remote").split()
    git(data_dir, "remote", "set-url" if "origin" in remotes else "add", "origin", remote)
    check_push_targets(data_dir, allow_unverified)
    # Attaching a new machine/folder to an existing site repo: adopt its history.
    if fresh and git(data_dir, "ls-remote", "--heads", "origin", "main", check=False):
        git(data_dir, "fetch", "-q", "origin", "main")
        check_local_matches_remote(data_dir, "origin/main")
        git(data_dir, "checkout", "-q", "-f", "-B", "main", "origin/main")
        git(data_dir, "branch", "-q", "--set-upstream-to", "origin/main")
    refresh_gitignore(data_dir)
    if not (data_dir / "README.md").exists():
        (data_dir / "README.md").write_text(README, encoding="utf-8")
    git(data_dir, "add", "-A")
    if git(data_dir, "status", "--porcelain"):
        git(data_dir, "commit", "-q", "-m", "Initialise site configuration repo")
    git(data_dir, "push", "-u", "origin", "main")
    print(f"Site config repo ready in {data_dir} -> {remote}")


def cmd_push(data_dir: Path, message: str | None, allow_unverified: bool = False) -> None:
    if not (data_dir / ".git").exists():
        sys.exit("Not initialised. Run `init --remote URL` first.")
    check_push_targets(data_dir, allow_unverified)
    branch = git(data_dir, "rev-parse", "--abbrev-ref", "HEAD")
    if branch == "HEAD":
        sys.exit("Not on a branch (detached HEAD). Check out main first.")
    refresh_gitignore(data_dir)
    git(data_dir, "add", "-A")
    if not git(data_dir, "status", "--porcelain"):
        print("No config changes to push.")
        return
    git(data_dir, "commit", "-q", "-m", message or "Update site configuration")
    git(data_dir, "push", "origin", branch)
    print("Pushed:", git(data_dir, "log", "--oneline", "-n", "1"))


def cmd_pull(data_dir: Path) -> None:
    git(data_dir, "pull", "--ff-only")
    print("Pulled. Restart Stagewatch to load the updated config.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["init", "push", "pull", "status"])
    ap.add_argument("--data-dir", type=Path, default=None)
    ap.add_argument("--remote")
    ap.add_argument("-m", "--message")
    ap.add_argument("--allow-unverified-remote", action="store_true",
                    help="continue with a remote that is not recognised as GitHub (you vouch it is private)")
    args = ap.parse_args()
    data_dir = (args.data_dir or default_data_dir()).resolve()
    if args.command == "init":
        if not args.remote:
            sys.exit("init needs --remote URL (a PRIVATE repository)")
        cmd_init(data_dir, args.remote, args.allow_unverified_remote)
    elif args.command == "push":
        cmd_push(data_dir, args.message, args.allow_unverified_remote)
    elif args.command == "pull":
        cmd_pull(data_dir)
    else:
        print(data_dir)
        print(git(data_dir, "status", "--short", "--branch", check=False) or "not a git repo")


if __name__ == "__main__":
    main()
